### ISSUE TITLE
Fix crazy retry-loop

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-rewards#5]
See #3

**Comment by elmigranto** [comment]
Easiest fix is to port events client to use `restify.JsonClient`, it has backoff retries for tcp errors (which is the one we have — can't establish connections). However, this still will lead to "busy loop" kind of problems with HTTP errors if we have those, but we can address those after current one.

Anyways, I was thinking we set up separate repos for `ganomede-clients` (and `ganomede-errors`). Can you create those under your GH acount?

**Comment by elmigranto** [comment]
On the other hand, IDK about making those 2 separate libs, maybe, we should rethink our `ganomede-helpers` situation. I guess we pretty confident about putting middlewares there was a mistake and `ganomede-boilerplate` is a better approach, but stuff like client classes and error classes feels different. Then again, API of `ganomede-events` might have a breaking change, and we'd have to reflect that in `helpers` lib and either:

  - bump its major version and change `EventsClient` API;
  - bump its minor version and add `EventsClientV2`.

I understand this is kind of wierd question, it seems at least a bit non-productive in a sense "let's make stuff work, why this discussion", but it feels important to me. What do you think?

**Comment by j3k0** [comment]
Yes it's important. I'm cautious with _shared libs_ because it ends up making stuff harder to manage in our micro-services situation. So here's what I think ;)

In my opinion, to make a lib out of some code, it has to be:

 - __limited in scope__: i.e. serve a __single__ well __delimited__ purpose.
 - __stable__: i.e. change very rarely.

For _ganomede-errors_, it's like only an extension of restify error, and nothing else. This matches those criteria. It can very well live in its own mini library.

Concerning ganomede client libraries, I don't like having them for all services in the same repository. Like I wouldn't like to use a single big library that can connect with any of redis, mysql and couchdb. I find it better to use small libs that handle a single service.

It also is convenient to have client libs alongside the server code:

 - a single PR. or release updates both server and client lib.
 - when deploying server version `v1.2.5`, pick client lib version `~1.2.5` to use it.

We can imagine the following situation:

 - I'm running a server with a old versions of service A and B (and many other)
 - I want to update to the latest of service B, so I do.
 - To use the new features, I have to upgrade a monolitic library in my app.
 - The newest monolitic library version expect a newer version of module "A". So I have no choice but to upgrade A too (and who knows: it might not be possible for some reasons...)

The situation becomes exponentially more potentially complex when we have about 20-30 different services running (which is our case).

Even if upgrading is possible, it's hard to predict what unrelated feature might break after upgrading the monolitic lib just when we wanted a single new feature of module B.

The above is not something to worry about when using different libs for ganomede-A and ganomede-B, etc.

So, that's my opinion ;-) Also that's what I like in the boilerplate approach vs. ganomede-helpers. ?Upgrading ganomede-helpers had too many potential effects in the app that it's hard to predict / test what will be the impact.

_personal happening: when reading env vars stopped working when I updated ganomede-helpers only to use restify v4... upgrading restify shouldn't break reading env vars! (but both things were linked due to ganomede-helpers)_

**Comment by j3k0** [comment]
This is what I mean: keeping relations between modules to a minimum is how we achieve modularity. This helps us stay sane when managing large systems. Last week on twitter: https://twitter.com/simonbrown/status/847339104874381312

**Comment by elmigranto** [comment]
Say we have a breaking change and `ganomede-events` is now `v2`. What I was thinking is we write `ganomedeClients.exports.EventsV2 = class EventsV2` without touching `v1` client. You propose the same, but instead it's same distinct client lib with different major version. I've no strong feelings either way, the fact that we use Node.js both on client and server (in relation to our services) allows us do to any of those.

On the other hand, copying `Base*` stuff back and forth is wierd. Maybe problem with `helpers` was that we indeed put too much and too different of a stuff into it. Like service env reader feels okay there, but those middlewares and server creation certainly don't.

Right now, we have this `BaseClient` class that's pretty good place, I think, to handle all the wierd/hard stuff we need:

  - [x] restify takes `baseUrl`, but for some reason discards `pathname` on it (like our `/<service>/v1`);
  - [ ] restify can't specify headers on per-request basis (`X-Request-Id`);
  - [ ] we need to add a way for clients to allow retries with backoffs on HTTP errors (maybe options arg, maybe something else).

I think you'd agree these shouldn't be in client libs, and manually syncing changes across all copies wouldn't make our life easier. Also, I don't really see a difference between, say, `npm install ganomede-base-client` vs `npm install request`. So maybe this is best approach?

I think we both feel that's the answer somewhere in the middle, and the question whether to "lib" or to "boilerplate" it depends on what *it* is, so:

  - **boilerplate** if changing something does not mean the change should propagate to everywhere else (like `create-server` function — if service X wants to disable logging all together doesn't mean service Y does too);
  - **lib** (whichever granularity we choose) otherwise (like `ServiceEnv`, or `BaseClient`, or `GanomedeError` — if we ever change those it's either a bug or some change we probably should introduce everywhere else);
  - don't mix the above stuff in one place.

**Comment by j3k0** [comment]
> Say we have a breaking change and ganomede-events is now v2

The problem with that is that we might make non-breaking server-side changes: like adding a new endpoint, that doesn't require a major version increase... but then we make use that new endpoint in a new version of the library, somehow that breaks the client if our deployment still runs an older version. This just requires to be extra cautious, but then we all make stupid things from time to time: inevitably we can forget about this in the excitation of building a new cool feature ;-)

Anyway. I'm 100% pro micro-libs: I don't see much downside to them. I wont repeat myself, ref. to what I consider good candidates to be libs. `node-servicenv`, `restify-advanced-jsonclient`, `ganomede-errors` are all good candidates.

Also, when some code becomes a lib, we have to provide extra documentation: the point of it being a lib is to be easy to integrate in different projects by copy-pasting some base use-case and going through README in diagonal. If that's more complicated than that, we --developers-- often found ourselves believing it's easier to build our own solution.

Creation of a new repo, configuring circleci and coveralls, managing the extra project, all of that require additional efforts: so not everything should be libs... Boilerplate is then a good middle-ground solution.

Lastly, anything that might improve a lib we use (like restify's JsonClient, restify's Errors), might be worth bringing up to those respective projects (as a discussion and/or a pull-request if maintainers find our proposals interesting)... If it makes it into those project, that's one less lib for us to manage, and a cool contribution to open-source!
